#########################################################################
# Title:            Sandbox: multiwordpress                             #
# Author(s):        Azlaroc                                             #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Task file to generate SSL certificates and set ownership

- name: Create directory for SSL certificate
  ansible.builtin.file:
    path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}"
    state: directory
    mode: '0755'

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}/private.key"
    mode: '0600'

- name: Generate certificate signing request (CSR)
  community.crypto.openssl_csr:
    path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}/request.csr"
    privatekey_path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}/private.key"
    common_name: "{{ multiwordpress_name }}"

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}/certificate.crt"
    csr_path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}/request.csr"
    privatekey_path: "{{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}/private.key"
    provider: selfsigned
    selfsigned_not_before: "-1d"
    selfsigned_not_after: "+365d"
    selfsigned_digest: "sha256"

- name: Ensure correct ownership of the SSL directory and files
  ansible.builtin.command:
    cmd: "chown -R 999:999 {{ multiwordpress_paths_certs }}/{{ multiwordpress_name }}"
  become: true
