#########################################################################
# Title:            Sandbox: multiwordpress                             #
# Author(s):        Azlaroc                                             #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Handlers file for multiwordpress role

- name: restart mariadb
  community.docker.docker_container:
    name: "{{ db_var }}"
    state: started
    recreate: true

- name: restart multiwordpress
  community.docker.docker_container:
    name: "{{ wb_var }}"
    state: started
    recreate: true